apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: v6venb77c-java-quarkus
  janus-idp.io/tekton: v6venb77c-java-quarkus
  backstage.io/kubernetes-id: v6venb77c-java-quarkus
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: v6venb77c-java-quarkus
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
